name: Build and Deploy Pom-Utils Maven Plugin

on: push

env:
  GITLAB_TOKEN: ${{ secrets.GITLAB_DEPLOY_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.REPOSITORY }}
  MAVEN_SETTINGS: ${{ github.WORKSPACE }}/settings.xml
  GIT_SUB_MODULE: pomutils-maven-plugin
  JAVA_VERSION: '19'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{env.JAVA_VERSION}}
          cache: 'maven'
          # server-id: gitlab-maven # Value of the distributionManagement/repository/id field of the pom.xml
          # settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build and test artifact
        run: |
          cd ${GIT_SUB_MODULE}
          mvn -s ${MAVEN_SETTINGS} clean install -P run-its
      - name: Deploy artifact
        run: |
          cd ${GIT_SUB_MODULE}
          mvn -s ${MAVEN_SETTINGS} deploy